spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dream?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: hLuN9VrQlKpTbDQ4DZ1/B17al45VAFFoNsX4J7BBIBMHnJ4ZShYtr/reNo8/fcrVWMxeFszvGRNKqHsmmfjpmA==
  thymeleaf:
    cache: true

# 密码公钥，生成请查看 net.dreamlu.druid.DruidPwdTools
publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ3jTsCgU3T5pbFXaIYGKjhbFgneTryPb9zKOum7pTIRlziVyysatc8CgQ2JFmKV++jhbX5lvXO2hLaJTZpuyg0CAwEAAQ==

dream:
  login:
    retry-limit: 1000
